[project]
name = "vequinox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "anthropic>=0.75.0",
    "datasets>=4.4.1",
    "llm-blender>=0.0.2",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "trl[judges]>=0.25.1",
]
